FROM php:7.3-cli
#FROM phpdockerio/php73-cli

RUN apt-get update && apt-get install --no-install-recommends -y \
    ca-certificates \
    locales tzdata \
    curl \
    zip \ 
    unzip \
    gettext \
    libgmp3-dev \
    libzip-dev libicu-dev libxml2-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && printf "de_DE.UTF-8 UTF-8\nen_US.UTF-8 UTF-8\n" > /etc/locale.gen \
    && locale-gen \
    && ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata

#RUN a2enmod rewrite

RUN docker-php-ext-install zip intl soap gettext gmp mysqli

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /application
CMD php -d short_open_tag=On -S 0.0.0.0:1024 -t public/ dev-router.php